#!/usr/bin/env ruby
# status:[ACTIVE] ver:[1.0.0] created:[26.03.13]
# doc:[PARTIAL] modified:[26.03.13] auth:[3OX.AI]
# Money.Bagz teleprompt — generate TPR config for TelePromptR merge

require 'json'
require 'fileutils'

ROOT = File.expand_path('../..', __dir__)
OUT = File.join(ROOT, '!0UT.BUDGET')
TPR = File.join(OUT, 'tpr')

def run
  FileUtils.mkdir_p(TPR)
  routes = JSON.parse(File.read(File.join(ROOT, '.3ox', '(5)Links', 'routes.json')))
  mesh = routes['mesh'] || {}
  tg = routes['telegram'] || {}

  # TPR speaker mesh config
  speaker = {
    'agent' => routes['agent'],
    'version' => routes['version'],
    'chat_id' => tg['chat_id'],
    'allowed_chat_ids' => tg['allowed_chat_ids'],
    'allowed_topics' => tg['allowed_topics'],
    'route' => mesh['route'],
    'config' => mesh['config']
  }
  File.write(File.join(TPR, mesh['config'] || 'TPR.SPEAKER.MESH.json'), JSON.pretty_generate(speaker))

  # TPR route map stub
  route_map = { 'agent' => routes['agent'], 'routes' => routes['routes'], 'topics' => tg['allowed_topics'] || [] }
  File.write(File.join(TPR, mesh['route'] || 'TPR.ROUTE.MAP.json'), JSON.pretty_generate(route_map))

  # merge.sh — merges into TelePromptR when TPR_ZENS3N points to repo
  merge_sh = <<~SH
    #!/usr/bin/env bash
    # Auto-generated by Money.Bagz teleprompt
    TPR_ROOT="${TPR_ZENS3N:-/root/!CMD.VPS}/TelePromptR"
    [[ -d "$TPR_ROOT" ]] || { echo "TelePromptR not found at $TPR_ROOT"; exit 1; }
    cp -f TPR.SPEAKER.MESH.json TPR.ROUTE.MAP.json "$TPR_ROOT/" 2>/dev/null || true
    echo "merge complete"
  SH
  File.write(File.join(TPR, 'merge.sh'), merge_sh)
  FileUtils.chmod(0755, File.join(TPR, 'merge.sh'))

  puts "teleprompt complete → !0UT.BUDGET/tpr/"
end
